# Generated by Django 6.1.1 on 2026-09-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_roomparticipant_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomparticipant',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
    ]
